apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-application
  namespace: argocd
spec:
  destination:
    namespace: app-ns
    server: https://kubernetes.default.svc
  project: default
  source:
    path: infra/argocd/sample-app/guestbook
    repoURL: https://github.com/Jefwillems/local-cluster-setup
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
