---
apiVersion: repo.github.upbound.io/v1alpha1
kind: Repository
metadata:
  name: hello-provider-github
spec:
  forProvider:
    name: hello-world-from-crossplane
    description: super awesome codebase!!
    visibility: public
    gitignoreTemplate: Terraform

    # securityAndAnalysis:
    #   - advancedSecurity:
    #     - status: enabled
    #     secretScanning:
    #     - status: disabled
    #     secretScanningPushProtection:
    #     - status: disabled  
  providerConfigRef:
    name: default