apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  project: default
  source:
    chart: istiod
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: "1.26"
    helm:
      values: |
        profile: ambient
        meshConfig:
          enablePrometheusMerge: true
          defaultConfig:
            tracing: {} # disable legacy MeshConfig tracing options
          extensionProviders:
            - name: jaeger
              opentelemetry:
                port: 4317
                service: jaeger-collector.istio-system.svc.cluster.local
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jsonPointers:
    - /webhooks/0/failurePolicy