apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/name: gitea-infra
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/name: gitea-infra
spec:
  parentRefs:
    - name: {{ .Values.name }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: gitea-infra-upstream-http
          port: 3000
