apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-application
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]

  generators:
  - git:
      repoURL: https://github.com/Jefwillems/local-cluster-setup.git
      revision: HEAD
      directories:
      - path: argocd/apps/*

  template:
    metadata:
      name: '{{.path.basename}}'
      labels:
        instance: '{{.path.basename}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/Jefwillems/local-cluster-setup.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'apps-ns'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true