additionalConfig:
  ignoreWebhookValidation: true

cni:
  profile: ambient

istiod:
  profile: ambient
  meshConfig:
    enablePrometheusMerge: true
    enableTracing: true
    defaultConfig:
      tracing: {} # disable legacy MeshConfig tracing options
    extensionProviders:
      - name: jaeger
        opentelemetry:
          port: 4317
          service: jaeger-collector.istio-system.svc.cluster.local
       