apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-of-infras
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/Jefwillems/local-cluster-setup.git
        revision: HEAD
        directories:
          - path: infra/argocd/infra/*
  template:
    metadata:
      name: "{{ "{{" }}.path.basename{{ "}}" }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/Jefwillems/local-cluster-setup.git
        targetRevision: HEAD
        path: "infra/argocd/infra/{{ "{{" }}.path.basename{{ "}}" }}"
        helm:
          valueFiles:
            - values.yaml
          ignoreMissingValueFiles: true
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ "{{" }}.path.basename{{ "}}" }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    {{ "{{" }}- if eq .path.basename "istio-system" {{ "}}" }}
    spec:
      ignoreDifferences:
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          name: istio-validator-istio-system
          jsonPointers:
            - /webhooks/0/failurePolicy
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          name: istiod-default-validator
          jsonPointers:
            - /webhooks/0/failurePolicy
    {{ "{{" }}- end {{ "}}" }}
