apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]

  generators:
    - git:
        repoURL: https://github.com/Jefwillems/local-cluster-setup.git
        revision: HEAD
        directories:
          - path: infra/argocd/apps/*
  template:
    metadata:
      name: "{{.path.basename}}"
      labels:
        instance: "{{.path.basename}}"
    spec:
      project: "default"
      source:
        repoURL: https://github.com/Jefwillems/local-cluster-setup.git
        targetRevision: HEAD
        path: "{{.path.path}}"
        helm:
          valueFiles:
            - values.yaml
          ignoreMissingValueFiles: true
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata:
          labels: # The labels to set on the application namespace
            istio.io/dataplane-mode: ambient

