apiVersion: v1
kind: Secret
metadata:
  name: gitea-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://gitea-infra-upstream-http.gitea-infra.svc.cluster.local:3000/admin/test.git
  name: gitea-repo
  project: default
  username: admin
  password: admin123
